### PR TITLE
Added in index on all_available_tdts.js

### PR DESCRIPTION
**Pull request by afmsavage**
for easier total

### CODE REVIEW

**Comment by knarz** [comment]
Danke! Will merge if you can rebase to latest master

**Comment by afmsavage** [comment]
done sir I really hate rebases but I suffered through it for the good of the project

**Comment by knarz** [comment]
And now you're using spaces instead of tabs for indentation!

**Comment by afmsavage** [comment]
That is the preferred way :(
ILL CHANGE IT SIR

**Comment by afmsavage** [comment]
ok please check @knarz

**Comment by knarz** [comment]
It's still not properly indented but I'll just fix it myself

**Comment by knarz** [comment]
Danke!

**Pull request merged**
